### PR TITLE
fix windows convert.exe and PEP8 linter

### PR DESCRIPTION
**Pull request by rexdf**
Windows has a builtin convert.exe  in `"C:\\Windows\\System32\\convert.exe"`. It's a util to convert disk from FAT32 to NTFS etc. We should avoid to call it.

PEP8 linter

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@rexdf if you're running `line.py` against PEP8, then every other Python file should be too.

**Comment by rexdf** [comment]
Other codes seem to have 4 space indention at least. Ok I'll check it again.

**Comment by rexdf** [comment]
Could I make a pull request with all run against PEP8? Or just patch Win convert?

**Comment by jbrooksuk** [comment]
Yeah, maybe do both separately if it's easier?

**Comment by rexdf** [comment]
The reason why I run PEP8 is that I need sublime to check when I type. The 2 spaces cause every line a red cross(error but not warning).

I've passed all errors and ommit several warning.

**Comment by rexdf** [comment]
sublime_python

**Comment by rexdf** [comment]
sublime_python_check

**Pull request closed without merging**
